// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpY1-FLtsPGtauiNsy2mFyONF9Uu9WYPc',
    appId: '1:414317402123:android:3d5f9d91a66f2ec80c4f0e',
    messagingSenderId: '414317402123',
    projectId: 'ppkormawa-3e5f0',
    databaseURL: 'https://ppkormawa-3e5f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ppkormawa-3e5f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZyFM7QhXsWCthnjciZtqKUKnh7G_iNhY',
    appId: '1:414317402123:ios:7a6e9af56c80d3900c4f0e',
    messagingSenderId: '414317402123',
    projectId: 'ppkormawa-3e5f0',
    databaseURL: 'https://ppkormawa-3e5f0-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ppkormawa-3e5f0.firebasestorage.app',
    iosBundleId: 'com.ppkormawa.flutterApplication1',
  );
}
